upmpdcli.conf.5: upmpdcli.conf-header.5 ../src/upmpdcli.conf-xml
	(cat upmpdcli.conf-header.5 && confxml --man ../src/upmpdcli.conf-xml && \
        cat upmpdcli.conf-trailer.5) > upmpdcli.conf.5
        
